// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskAPI.Data;

#nullable disable

namespace TaskAPI.Data.Migrations
{
    [DbContext(typeof(TaskDBContext))]
    [Migration("20221224061053_AuthorandTaskSeeder")]
    partial class AuthorandTaskSeeder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskAPI.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Kanchana Kariyawasam"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Buddhini Perera"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Sasindu Kariyawasam"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Parakrama Kariyawasam"
                        });
                });

            modelBuilder.Entity("TaskAPI.Models.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Due")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Todo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthordID = 1,
                            Due = new DateTime(2022, 12, 26, 11, 40, 52, 762, DateTimeKind.Local).AddTicks(7655),
                            Status = 1,
                            Todo = "Complete Java OOP Assignment"
                        },
                        new
                        {
                            Id = 2,
                            AuthordID = 1,
                            Due = new DateTime(2022, 12, 27, 11, 40, 52, 762, DateTimeKind.Local).AddTicks(7672),
                            Status = 0,
                            Todo = "Complete Database Assignment"
                        },
                        new
                        {
                            Id = 3,
                            AuthordID = 2,
                            Due = new DateTime(2022, 12, 30, 11, 40, 52, 762, DateTimeKind.Local).AddTicks(7674),
                            Status = 1,
                            Todo = "Complete XML Tutorial"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
